"""Create table Post, Comment

Revision ID: 2201620c5adc
Revises: 1c5fb24a3a7c
Create Date: 2025-12-06 22:24:23.919043

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2201620c5adc"
down_revision: Union[str, Sequence[str], None] = "1c5fb24a3a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables already created in migration 0b446e005cff
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables first - SQLite will automatically drop all indexes
    op.drop_table("comments")
    op.drop_table("posts")
    # ### end Alembic commands ###
